# Generated by Django 2.2 on 2019-04-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(verbose_name='date submitted')),
                ('response_text', models.CharField(max_length=65536)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quillcomp_web.Prompt')),
            ],
        ),
    ]
